services:
    marttiphpbb.replytemplate.acp_listener:
        class: marttiphpbb\replytemplate\event\acp_listener
        arguments:
            - '@dbal.conn'
            - '@request'
            - '@language'
            - '@marttiphpbb.replytemplate.service.store'
            - '%tables.forums%'
        tags:
            - { name: event.listener }

    marttiphpbb.replytemplate.posting_listener:
        class: marttiphpbb\replytemplate\event\posting_listener
        arguments:
            - '@marttiphpbb.replytemplate.service.store'
        tags:
            - { name: event.listener }

    marttiphpbb.replytemplate.service.store:
        class: marttiphpbb\replytemplate\service\store
        arguments:
            - '@config_text'
            - '@cache.driver'
